[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.supabase.co https://*.googleapis.com"

[functions]
  directory = "server"

[functions.environment]
  NODE_ENV = "production"

# Build hooks for deployment
[build.hooks]
  prebuild = "echo 'Starting Temporal Nexus deployment...'"
  postbuild = "echo 'Temporal Nexus build completed successfully!'"

# Performance optimizations
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Environment variables (set these in Netlify dashboard)
# GEMINI_API_KEY
# VITE_SUPABASE_URL
# VITE_SUPABASE_ANON_KEY
